SELECT M.NAME, M.LANGUAGE, M.DURATION_IN_MINUTES, M.RELEASE_DATE,
T.NAME, T.AREA, T.CITY, T.STATE, T.ADDRESS, TS.SCREEN_NUMBER, MS.SHOW_TIME
FROM MOVIE_SHOW MS, MOVIE M, THEATRE_SCREEN TS, THEATRE T 
WHERE MS.SHOW_TIME BETWEEN '2023-04-20 00:00:00' AND '2023-04-26 23:59:59'
AND MS.MOVIE_ID = M.ID
AND MS.THEATRE_SCREEN_ID = TS.ID
AND TS.THEATRE_ID = T.ID;